### ISSUE TITLE
Some thoughts about your config

### ISSUE THREAD

**Issue by mrkkrp** [snosov1/dot-emacs#1]
Случайно нашёл вашу конфигурацию и прочитал `README.org` файл. Хотя моя
собственная конфигурация сильно отличается от вашей, я позаимствовал пару
мелких вещей и решил "отплатить" вам.

---

> Hopefully, you will find something useful here and, maybe, you will share
> your insights into better ways to use Emacs with me.

Звучит как будто вы предлагаете поделиться идеями о том как лучше
использовать Emacs именно с вами :-)

---

``` emacs-lisp
(ignore-errors
  (set-frame-font
   (car (x-list-fonts "-*-DejaVu Sans Mono-normal-normal-normal-*-*-*-*-*-*-*-iso10646-1"))))
```

Странный способ выбрать шрифт. Как насчёт (может я чего-то не знаю):

``` emacs-lisp
(set-face-attribute 'default nil :family "DejaVu Sans Mono")
(set-face-attribute 'variable-pitch nil :family "DejaVu Sans Mono") ; optional
```

---

> Upcase, lowercase and capitalize

Скромно могу предложить [Fix Word](https://github.com/mrkkrp/fix-word).

---

``` emacs-lisp
(setq-default wdired-allow-to-change-permissions t)
```

Это не локальная по отношению к буферу переменная, поэтому просто `seq` было
бы достаточно.

---

Dired может обновляться автоматически если содержимое директории
меняется. Пробуйте:

``` emacs-lisp
(setq auto-revert-verbose nil
      global-auto-revert-non-file-buffers t)

(global-auto-revert-mode 1) ; revert buffers automatically
```

---

``` emacs-lisp
(define-key global-map (kbd "\C-c f")
  (defun toggle-window-split ()
    "Switches from a horizontal split to a vertical split and visa versa."
    (interactive)
    …))
```

Visa Versa! Забавная опечатка.

---

> Embedded lisp evaluation

В Emacs есть замечательный калькулятор.

---

> Now we’re getting on speed. Once you already have multiple cursors, M-#
> adds successive numbers in the place of each cursor. E.g. if you have 3
> cursors, then pressing M-# will print 0 in the position of the first
> cursor, 1 - in the position of the second cursor and 2 - in the position
> of the third cursor. If you provide a prefix argument, say, C-3 M-#, it
> will be used as a base number - 3, 4, 5.

Это делается через прямоугольное выделение (в Emacs 25 теперь есть
визуальная поддержка для этого, <kbd>C-x SPC</kbd> — если использовать
горячие клавиши по умолчанию), потом `rectangle-number-lines`. Для меня это
<kbd>menu r n</kbd>, т.к. <kbd>M-x …</kbd> — слишком медленно.

---

Всегда удивляюсь когда люди используют горячие клавиши Emacs, которые там
поставлены по-умолчанию. У вас нет болей в руках? Как можно нажимать
несколько клавиш одновременно? Это же идёт в разрез со всякой
эргономикой. Посмотрите на кассовые аппараты и т.п. — специализированные
машины, которые специально разработаны для одной конкретной цели. Все
операции выполняются одним нажатием клавиши или их
последовательностью. Аккорды должны быть исключены полностью :-) Тоже самое
и для <kbd>⇧ Shift</kbd>. Всё пережитки времен печатной машинки — тогда надо
было держать клавишу из-за конструктивных особенностей машинки, а сейчас зачем?
Мне нравится идея чтобы <kbd>⇧ Shift</kbd> поднимал _следующую_ букву,
т.е. нажимался перед ней, а не вместе с ней. Но я понимаю что мои взгляды и
методы использования Emacs немного маргинальны, так что это просто мнение.

---

Русскоязычные сочинения читать не стал, т.к. явно написано не для меня + я
не могу читать когда обращаются на ты.

---

Ах да, тире, которое ‘—’ — оно отличается от дефиса, который ‘-’, хорошо бы
использовать каждого по назначению, сразу лучше смотрится.

---

Удачи!

**Comment by snosov1** [comment]
> Звучит как будто вы предлагаете поделиться идеями о том как лучше
> использовать Emacs именно с вами :-)

Спасибо за ценные советы!

> Странный способ выбрать шрифт. Как насчёт (может я чего-то не знаю):

Поменял у себя. Это была одна из самых первых моих записей - сделал первым способом, который нашел.

> Скромно могу предложить Fix Word.

Я наталкивался на этот пакет, но мне кажется, что превращать `fo^o` в `foO^` правильнее, чем в `FOO`. Возможно, конечно, что это только привычка, но тем не менее. =)

> Это не локальная по отношению к буферу переменная, поэтому просто seq было
> бы достаточно.

В какой-то момент я осознанно перестал использовать `customize`. По умолчанию (насколько мне известно) он использует `setq-default`, поэтому при переписывании я тоже везде использовал `setq-default`. Я так понимаю разницы в данном случае никакой нет.

> Dired может обновляться автоматически если содержимое директории
> меняется.

Неплохо, но мне ещё нужно подумать стоит его включать или нет. Если всё-таки включать, то надо ставить интервал обновления в районе 0.1 с. Не уверен насколько это дорого. Плюс, если раньше мне не очень нравилось, что Dired не обновляется сам, то теперь я привык настолько, что мне уже вроде бы это нравится =)

> Visa Versa! Забавная опечатка.

Fixed

> В Emacs есть замечательный калькулятор.

Это да. Но он хорош только как калькулятор. Иногда какие-то вычисления нужно записать на диск, иногда хочется более свободно работать с вычисляющим текстом. Плюс, например, если в файле записаны 100 чисел, которые надо сложить, то копировать их туда-сюда не очень удобно, а добавить перед ними плюс, заключить их в скобки `(+ 10 2 3 1 4 ...)` и вычислить - очень даже.

> Это делается через прямоугольное выделение (в Emacs 25 теперь есть
> визуальная поддержка для этого, C-x SPC — если использовать
> горячие клавиши по умолчанию),

Вообще говоря, да. Но (теоретически) дополнительные курсоры - это то же самое, плюс ещё немало чего. Я пользовался прямоугольными регионами до того, как перешел на дополнительные курсоры, и как-то почти перестал пользоваться после. Единственное, иногда, когда курсоров слишком много - они начинают подтормаживать, а прямоугольные регионы работают нормально - я пользуюсь ими. 

> т.е. нажимался перед ней, а не вместе с ней. Но я понимаю что мои взгляды и
> методы использования Emacs немного маргинальны, так что это просто мнение.

Мне кажется они у всех пользователей Emacs маргинальны. Возможно, потому что сами пользователи все - маргиналы =)

Так или иначе, не уверен, что я целиком понял вопрос. Но ответ такой - Ctrl у меня находится на месте Caps Lock'a и, собственно, в этом весь секрет (т.е. никакого секрета на самом деле нет). Мои пальцы не считают, что печатать большими буквами с нажатым Shift'ом - это что-то страшное. Точно также и нажимать постоянно Caps Lock (как `C-`) мне не доставляет какого то дискомфорта. 

Я пробежался глазами по описанию, которое у Вас в конфиге написано и нашел 2 существенных отличия что ли (может быть их больше) - использование кнопок F1, F2 и т.д. и залипающие модификаторы + "последовательности нажатий". 

Использование клавиш F1, F2 и т.д. при разговорах об эргономике у меня вообще всегда вызывает некоторое недоумение (как и использование ESC пользователями Vim - тоже из эргономических соображений). Т.е. как бы - где F2 и где мои руки. Я сохраняю файл каждый 5 секунд, наверное. Т.е. мне каждые пять секунд надо тянуться на самый верх клавиатуры? По-моему что-то тут не то. Может оно, конечно, и не хуже, чем `C-x C-s`, но уж точно и не лучше, как мне кажется.

К залипающим клавишам у меня вопросов меньше - т.е. концепция понятная и нормальная - но мне она просто не нравится (см. вкусовщина). Это как бы часть общих моих предпочтений не иметь во время редактирования какого-то "состояния". Т.е. мне нравится, когда одни и те же кнопки делают всегда одно и то же вне зависимости от того, что было до этого. Залипающие клавиши не сильно этому мешают (не так, например, как моды в Vim'e), но всё же. 

> Русскоязычные сочинения читать не стал, т.к. явно написано не для меня 

Да, там для тех, кто совсем не в теме. Даю читать коллегам и студентам. Некоторым вроде помогает.

> - я не могу читать когда обращаются на ты.

В этом ответе писал на "ты", но после такого предупреждения переписал на "Вы". =)

> Ах да, тире, которое ‘—’ — оно отличается от дефиса, который ‘-’, хорошо бы
> использовать каждого по назначению, сразу лучше смотрится.

Другой ревнитель грамотности, который по этому поводу тоже переживает - Д. Кнут. Озабочусь этим вопросом, когда дорасту до его уровня =)

Тем не менее, спасибо =)

**Comment by mrkkrp** [comment]
> Неплохо, но мне ещё нужно подумать стоит его включать или нет. Если
> всё-таки включать, то надо ставить интервал обновления в районе 0.1 с. Не
> уверен насколько это дорого. Плюс, если раньше мне не очень нравилось, что
> Dired не обновляется сам, то теперь я привык настолько, что мне уже вроде
> бы это нравится =)

Привычка — сильная штука. Может развиться привычка тянуться до F-клавиш иной
раз :)

---

> Это да. Но он хорош только как калькулятор. Иногда какие-то вычисления
> нужно записать на диск, иногда хочется более свободно работать с
> вычисляющим текстом. Плюс, например, если в файле записаны 100 чисел,
> которые надо сложить, то копировать их туда-сюда не очень удобно, а
> добавить перед ними плюс, заключить их в скобки (+ 10 2 3 1 4 ...) и
> вычислить - очень даже.

Оба способа работают. Справедливости ради следует отметить, что калькулятор
имеет набор команд чтобы «забирать» и вставлять обратно данные.

---

> Так или иначе, не уверен, что я целиком понял вопрос. Но ответ такой -
> Ctrl у меня находится на месте Caps Lock'a и, собственно, в этом весь
> секрет (т.е. никакого секрета на самом деле нет). Мои пальцы не считают,
> что печатать большими буквами с нажатым Shift'ом - это что-то
> страшное. Точно также и нажимать постоянно Caps Lock (как C-) мне не
> доставляет какого то дискомфорта.

Перенос <kbd>⎈ Ctrl</kbd> облегчает, но не решает проблемы,
т.к. проблема в том что нужно нажимать эту клавишу мизинцем (и много), а
мизинец — самый слабый палец. <kbd>⎈ Ctrl</kbd> должен быть внизу, чтобы
нажимать его ладонью. Вот тут есть про это:
http://ergoemacs.org/emacs/swap_CapsLock_Ctrl.html

Но это только для нормальных клавиатур, не для ноутбуков. Для ноутбуков надо
другие решения чтобы разгружать мизинец, как например то что я
использую. Ещё хорошо привыкнуть к пакету типа `ace-jump-mode` или `avy`
(улучшенная версия первого). По-началу странно (как и всё остальное), но
может сократить нагрузки.

---

> Использование клавиш F1, F2 и т.д. при разговорах об эргономике у меня
> вообще всегда вызывает некоторое недоумение (как и использование ESC
> пользователями Vim - тоже из эргономических соображений). Т.е. как бы -
> где F2 и где мои руки. Я сохраняю файл каждый 5 секунд, наверное. Т.е. мне
> каждые пять секунд надо тянуться на самый верх клавиатуры? По-моему что-то
> тут не то. Может оно, конечно, и не хуже, чем C-x C-s, но уж точно и не
> лучше, как мне кажется.

Не люблю спорить, но всё-же вот кое-какие аргументы:
- клавиши эти не так уж далеко, а сохранять нужно не так уж часто (раз в
  пол-минуты, это наверное реальная оценка, хотя иногда чаще), то же самое
  убивать буфер гораздо приятнее одним нажатием, и это не так часто нужно
  делать (относительно), то же самое с открытием файла, смысл в том что эти
  операции по-определению нужны не так часто как те что участвуют в
  редактировании;
- единственная клавиша всегда эффективнее чем аккорд типа <kbd>C-x C-s</kbd>
- в самом деле, кто может отказаться от 12 дополнительных клавиш, которые
  можно назначить на что угодно?

---

> В этом ответе писал на "ты", но после такого предупреждения переписал на
> "Вы". =)

Просто «вы» даёт дистанцию, хотя некоторые люди не чувствуют когда она
нужна. В таких текстах я считаю всегда нужно использовать обращение на «вы»,
т.к. неизвестно кто ваш конечный читатель, может он старше вас, а вы ему
тыкаете. И кстати «вы» с большой буквы — это тоже довольно плохо. Сейчас
распространено стало, даже в более или менее приличных местах. Дело в том,
что когда человека ставят во множественное число, это уже означает большу́ю
степень уважения к нему, а некоторые люди, например из области рекламы,
хотят таки задавить вас своим мнимым уважением, так что пишут с большой
буквы к тому же. А «вы» — это не имя собственное, это просто ошибка писать
так.

Довольно интересно, что в английском нет обращений на «ты» например (хотя
некоторые будут утверждать что там наоборот обращаются только на «ты», и
дескать нам тоже надо проще быть, это всё от незнания языка, достаточно
посмотреть на спряжения глаголов «be» и «have»). Язык этот прямо таки создан
со встроенной вежливостью, но он проигрывает от этого тоже, потому как
близкие обращения тоже должны быть.

Английский язык вообще иногда кажется немного искусственным в его
структурированности и отсутствии некоторых вещей, типа возвратных глаголов,
а спряжение глаголов — это просто винегрет, т.к. часть времен образуется
добавлением отдельных слов, другая часть изменением окончаний, к тому же
некоторые глаголы просто имеют более сложные правила спряжения, чем
другие. К тому же нет понятия рода существительных. Весь язык построен по
«ad hoc» принципу. На всё это не обращаешь внимания пока не начнёшь изучать
французский к примеру, который довольно похож на русский по многим
параметрам и от этого выглядит естественнее. А как только начнёшь учить
что-то вроде французского, понимаешь насколько красив русский язык, хотя
многие сейчас предпочитают английский, даже там где его не нужно. Это такая
рефлексия через изучение чужого, начинаешь снаружи видеть свой язык и
понимать как он прекрасен.

Ладно, что-то я заговорился :-D

---

Как долго вы используете Emacs? С какого примерно года? Я вижу что
конфигурация долго «откладывалась», если можно так выразиться.

**Comment by snosov1** [comment]
> Оба способа работают. Справедливости ради следует отметить, что калькулятор
> имеет набор команд чтобы «забирать» и вставлять обратно данные.

Мне самому калькулятор откровенно нравится, но сильно чувствуется, что его как написали лет 30 назад, так он с тех пор в том виде и живет. Функциональность богатая и толковая, но как-то не совсем удобно - надо приноравливаться, а руки не доходят.

> Перенос ⎈ Ctrl облегчает, но это не решает проблемы,

Я понимаю о чем Вы говорите, но, наверное, это индивидуальный момент. Т.е. я искренне не чувствую никакого дискомфорта - у меня "аккорды" с Ctrlом-CapsLockом нажимаются естественно, хотя я и понимаю, что, наверное, это не совсем правильно с точки зрения "печатной науки". Может быть, если бы я скорость хотел развить раза в 2-3 выше, чем имею (а имею около 50-60 WPM), то пришлось бы что-то менять, а так - не чувствую необходимости.

> ⎈ Ctrl должен быть внизу, чтобы нажимать его ладонью

Про это я тоже читал, но тут, по-моему, даже "печатная наука" должна автора этой статьи расстрелять =) Ну т.е. опять же всё индивидуально, но для меня жать Ctrl ладонью - за гранью добра и зла.

> Но это только для нормальных клавиатур, не для ноутбуков

Не знаю, я всю жизнь работаю и на ноутбучных и на "обычных" клавиатурах, на рабочем компьютере у меня Natural Ergonomic 4000 - разницу между ними, честно говоря, практически не улавливаю. 

>  Ещё хорошо привыкнуть к пакету типа ace-jump-mode

У меня с ним как-то не срослось. Пользоваться incremental search'ем мне гораздо удобнее.

> Не люблю спорить, но всё-же вот кое-какие аргументы:

Ну вот лично я страдаю каждый раз, когда мне нужно пальцы переместить с "home position". Я и на Emacs то перешел в большей части из-за того, что уже не мог жать стрелочки постоянно. Соответственно, мне гораздо удобнее нажать любой аккорд, чем рукой дотянуться до ряда с кнопками F-. Потому так и живу. Т.е. я аргументы понимаю, но не принимаю - они не про меня =)

> Просто «вы» даёт дистанцию, хотя некоторые люди не чувствуют когда она нужна

А мне хочется быть ближе к читателю =) Я его не знаю, он меня тоже - мы с ним вообще не общались ни разу, наверняка - куда уж там ещё отдаляться. Но это не главное. При таком "заочном" общении не очень просто донести то, что хочешь сказать. Если ещё разбавить это реверансами и раскланиваниями - то суть в них теряется ещё больше. Поэтому я предпочитаю писать прямо и без лишних слов. Если читатель обладает интеллектом - то обидеть его этим невозможно. 

> И кстати «вы» с большой буквы — это тоже довольно плохо.

Об этом я и говорю =) если начать разбираться, где ставить дефис, а где чёрточку, где "вы" с большой, а где с маленькой - можно забыть, о чем хотел написать. На мой взгляд, когда смысловой разницы нет - то всё равно, что написать "Вы", "вы", "ты", "достопочтенный читатель", "дорогой друг" - поэтому особо не задумываюсь. (Если только это не нужно для придания соответствующего художественного окраса).

> Как долго вы используете Emacs? С какого примерно года? Я вижу что
> конфигурация долго «откладывалась», если можно так выразиться.

С 2012 года примерно. Т.е. около трех лет. Конфигурацию активно писал первые год-полтора. Потом, когда понял, что она более или менее устоялась - превратил в некую само-документированную сущность.

**Comment by mrkkrp** [comment]
> Если читатель обладает интеллектом - то обидеть его этим невозможно.

Да, чем выше интеллект, тем обидеть сложнее, если «обидеть» — это правильное
слово здесь :)

> Об этом я и говорю =) если начать разбираться, где ставить дефис, а где
> чёрточку, где "вы" с большой, а где с маленькой - можно забыть, о чем
> хотел написать. На мой взгляд, когда смысловой разницы нет - то всё равно,
> что написать "Вы", "вы", "ты", "достопочтенный читатель", "дорогой друг" -
> поэтому особо не задумываюсь. (Если только это не нужно для придания
> соответствующего художественного окраса).

Об этом много и дельно (а может и нет) можно было бы поговорить. Роль
деталей трудно переоценить в любом деле (из тех в каких я сведущ).

Спасибо за беседу.

**Comment by snosov1** [comment]
Да, спасибо!

**Comment by mrkkrp** [comment]
Ещё одна вещь, я вижу вы прилагаете некоторые усилия чтобы после открытия строки выравнивание держалось и т.п., как насчёт того чтобы убрать все эти ухищрения, но добавить вот этот пакет: https://github.com/Malabarba/aggressive-indent-mode . Сегодня на него наткнулся, вроде бы можно пользоваться. До этого я использовал electric-indent, хотя выравнивание и отступы в некоторых языках имеют семантическое значение, поэтому там такое всё равное не применимо, я отключаю для Python и Haskell, например.

**Comment by snosov1** [comment]
Я несколько несогласен с подобными подходами. В том плане, что вдруг автоматическое выравнивание делает не то, что нужно. Для лиспа это не очень актуально, но в С++, например, синтаксис не всегда хорошо парсится и авто-выравнивание просто ошибается. Или, бывает я редактирую чужой код и мне надо сохранить чужое выравнивание. Или в каких-то редких случаях мне хочется выравнить не совсем по правилам, чтобы было более красиво. Если выравнивание срабатывает на нажатие любой клавиши - придется как-то ухищряться, чтобы от него избавиться. 

Т.е. сейчас я ухищряюсь, указывая случаи, когда мне нужно авто-выравнивание. А если включить агрессивную стратегию, то придется ухищряться в случаях, когда оно будет не нужно. Не уверен, что это сильно лучше =)

**Comment by mrkkrp** [comment]
Понятно. А я сейчас работаю в основном с функциональными языками, это всякие лиспы, для которых авто-выравнивание работает отличино, а для Haskell и Python это всё равно не годится. А у C++ синтаксис волосат, конечно, не удивительно что парсеры не всегда справляются, тут человек-то иной раз не выдерживает :)

А чем `smooth-scroll` не годен с вашей точки зрения?

**Comment by snosov1** [comment]
> А я сейчас работаю в основном с функциональными языками, это всякие лиспы, для которых авто-выравнивание работает отличино,

Тут да, всё гораздо проще.

> А чем smooth-scroll не годен с вашей точки зрения?

Я не очень знаком, поэтому не знаю. Идея нормальная - но дело вкуса и привычки. "Прыжков" у меня нет - скролится по одной строчке, а для того, чтобы "контекст" было видно - жму `C-l`, когда дошел докуда надо. Так что для себя просто не вижу особого смысла.

**Comment by mrkkrp** [comment]
У вас кстати всё ещё имеются кусочки не идиоматического лиспа, они видимо
старые, например:

``` emacs-lisp
(funcall
 (defun configure-theme ()
   "Make Emacs pretty"
   (load-theme 'tango-dark)
   (enable-theme 'tango-dark)
   ;; make background a little bit darker
   (set-background-color "#1d1f21")
   (setq-default frame-background-mode (quote dark))))
```

Вы зачем-то пишете функцию и тут же её вызываете, хотя больше она нигде не
используется и она не является командой. Можно бы просто:

``` emacs-lisp
(load-theme 'tango-dark)
(enable-theme 'tango-dark)
;; make background a little bit darker
(set-background-color "#1d1f21")
(setq-default frame-background-mode (quote dark))))
```

Потом, `load-theme` по-умолчанию применяет загружаемую тему, если не дан
дополнительный аргумент, а вот другой дополнительный аргумент избавляет от
подтверждения загрузки:

``` emacs-lisp
(load-theme 'tango-dark t)
(set-background-color "#1d1f21")
(setq-default frame-background-mode (quote dark))
```

Теперь, вы знаете что делает третья строчка? Какую разницу она вносит? Я —
нет. Её тоже можно убрать, я уверен.

``` emacs-lisp
(load-theme 'tango-dark t)
(set-background-color "#1d1f21")
```

Теперь, я просто хочу посоветовать посмотреть на тему `solarized-dark`. Эти
темы специально разработаны чтобы снизить нагрузку на глаза. Вот тут есть об
этом:

http://ethanschoonover.com/solarized

Я могу сказать что действительно с этой темой легче работать, по крайней
мере мне.

Вот эта реализация получше:

https://github.com/bbatsov/solarized-emacs

**Comment by snosov1** [comment]
> У вас кстати всё ещё имеются кусочки не идиоматического лиспа,

Это идиома собственного сочинения, рожденная многолетним программированием на С++. С++ блочный язык - и я таким способом как бы создаю блок. В лиспе-то особого смысла в этом нет, но как бы получается, что я кусок объединяю не только тем, что рядом вызовы написаны, но ещё и синтаксически.

> Потом, load-theme по-умолчанию применяет загружаемую тему, если не дан
> дополнительный аргумент, а вот другой дополнительный аргумент избавляет от
> подтверждения загрузки:

Поправил.

> Теперь, вы знаете что делает третья строчка? Какую разницу она вносит? Я —
> нет.

Некоторые моды в зависимости от её значения меняют цвет шрифтов и фонов. Т.е. у них есть набор цветов, который хорошо смотрится на светлом фоне и набор цветов, который хорошо смотрится на темном. И они выбирают соответствующий. Я не помню точно для какого мода я в первый раз её выставил, но смысл такой.

> Эти темы специально разработаны чтобы снизить нагрузку на глаза. 

Мне кажется, что такие вещи слишком индивидуальны, чтобы можно было разработать какую-то тему, которая бы подходила всем. (Одна история про бело-золотое платье чего стоит). Наверное, можно повысить процент людей, которым она подходит, но он всё равно будет далек от 100. Я много тем пробовал, в т.ч. solarized, против которого опять же ничего не имею, но почему-то вот с tango мне лучше всего (если фон ещё темнее сделать). 

Хотя сейчас опять смотрю скриншоты solarized и думаю, может быть стоит дать ей второй шанс =)

**Comment by mrkkrp** [comment]
Понятно, не склонить мне вас сегодня ни к чему, видимо :-D

**Comment by snosov1** [comment]
Ну - я по мелочи всякое поправил. И про solarized задумался - может быть во что-то выльется =) Спасибо =)

**Comment by mrkkrp** [comment]
Я вспомнил ещё кое-что по внешнему виду:

``` emacs-lisp
(add-hook 'dired-mode-hook   #'hl-line-mode)
(add-hook 'ibuffer-mode-hook #'hl-line-mode)
```

Это включает подсвечивание текущей строки в Dired и iBuffer. Я это давно
придумал, не видел чтобы кто-нибудь делал что-то подобное, хотя вполне
очевидно.

**Comment by snosov1** [comment]
Неплохо. Но по умолчанию с моей темой выглядит не очень - курсор сливается
с выделением. Сделаю черным (как в магите) - погляжу, как пойдет.

## 

Best regards,
       Sergei Nosov

2015-06-11 13:22 GMT+03:00 Mark Karpov notifications@github.com:
